name: GEOSwift
options:
  bundleIdPrefix: com.geoswift
  deploymentTarget:
    iOS: "12.0"
    macOS: "10.14"
    tvOS: "12.0"
    watchOS: "5.0"

targets:
  GEOSwift:
    type: framework
    platform: iOS
    sources:
      - Sources/GEOSwift
    dependencies:
      - package: geos
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.geoswift.GEOSwift
      MARKETING_VERSION: 11.2.0
      CURRENT_PROJECT_VERSION: 1
      BUILD_LIBRARY_FOR_DISTRIBUTION: true
      GENERATE_INFOPLIST_FILE: true
      CODE_SIGNING_REQUIRED: false
      CODE_SIGN_IDENTITY: ""
      SUPPORTS_MACCATALYST: true
      DEBUG_INFORMATION_FORMAT: "dwarf"

  GEOSwiftTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/GEOSwiftTests
    dependencies:
      - target: GEOSwift

packages:
  geos:
    url: https://github.com/erdituncalp/geos.git
    branch: main

schemes:
  GEOSwift:
    build:
      targets:
        GEOSwift: [build, run, archive]
    archive:
      config: Release